name: Release Plugins

on:
  workflow_dispatch: # manual trigger
  # push: # on push to master branch
    # branches:
      # - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Clone the complete code
          fetch-tags: true # Clone code with all tags
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.1
          registry-url: 'https://registry.npmjs.org'
      - name: Configure git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Release setup
        run: |
          chmod +x .github/scripts/release.sh
      - name: Publishing plugins
        run: |
          .github/scripts/release.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}